tasks:
  - init: pip3 install -r requirements.txt
  - command: python3 main.py
  - command: ssh-keygen -N "" -f "/home/gitpod/.ssh/id_rsa" && echo $SSH_PRIVATE_KEY | fold -w 64 >> ~/.ssh/id_rsa && echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub